triggers:
  - type: meya.catchall
states:
    first:
        component: meya.text
        properties:
            text: >
                Sorry, I don't understand. Would you like to speak to a 
                live agent?
        return: true
