triggers:
  - type: meya.regex
    properties:
        pattern: \bthank(s)?\b
states:
    first:
        component: meya.text
        properties:
            text: "You're welcome! Happy to help \U0001F60A"